### ISSUE TITLE
Help me to understand issue Incompatible units: 'rem' and 'px'.

### ISSUE THREAD

**Issue by pareshsojitra** [DevExpress/bootstrap-themes#17]
Error in plugin "sass"
Message:
    node_modules\bootstrap\scss\_variables.scss
Error: Incompatible units: 'rem' and 'px'.
        on line 593 of node_modules/bootstrap/scss/_variables.scss
        from line 9 of node_modules/bootstrap/scss/bootstrap.scss
        from line 2 of dist/blazing-berry/blazing-berry.scss
>> edback-icon-padding-right: add(1em * .75, (2 * $custom-select-padding-y * .7
   ------------------------------------------^

[13:19:57] 'compile-blazing-berry' errored after 87 ms
[13:19:57] Error in plugin "gulp-sass"
Message:
    node_modules\bootstrap\scss\_variables.scss
Error: Incompatible units: 'rem' and 'px'.
        on line 593 of node_modules/bootstrap/scss/_variables.scss
        from line 9 of node_modules/bootstrap/scss/bootstrap.scss
        from line 2 of dist/blazing-berry/blazing-berry.scss
>> edback-icon-padding-right: add(1em * .75, (2 * $custom-select-padding-y * .7
   ------------------------------------------^

Details:
    status: 1
    file: D:/wamp64/www/html_build/node_modules/bootstrap/scss/_variables.scss
    line: 593
    column: 60
    formatted: Error: Incompatible units: 'rem' and 'px'.
        on line 593 of node_modules/bootstrap/scss/_variables.scss
        from line 9 of node_modules/bootstrap/scss/bootstrap.scss
        from line 2 of dist/blazing-berry/blazing-berry.scss
>> edback-icon-padding-right: add(1em * .75, (2 * $custom-select-padding-y * .7
   ------------------------------------------^

    messageFormatted: node_modules\bootstrap\scss\_variables.scss
Error: Incompatible units: 'rem' and 'px'.
        on line 593 of node_modules/bootstrap/scss/_variables.scss
        from line 9 of node_modules/bootstrap/scss/bootstrap.scss
        from line 2 of dist/blazing-berry/blazing-berry.scss
>> edback-icon-padding-right: add(1em * .75, (2 * $custom-select-padding-y * .7
   ------------------------------------------^

    messageOriginal: Incompatible units: 'rem' and 'px'.
    relativePath: node_modules\bootstrap\scss\_variables.scss
    domainThrown: true

[13:19:57] 'default' errored after 3.52 s

**Comment by Nelda4** [comment]
Hi

Thank you for pointing this out. I reproduced this problem and fixed it. Would you please check the current version and let us know whether you have any difficulty with it?

**Comment by pareshsojitra** [comment]
Its works fine now, Thank you so much.
