### ISSUE TITLE
Customize validation colors

### ISSUE THREAD

**Issue by sven5** [DevExpress/bootstrap-themes#30]
Hi guys,

Currently I came across one issue. We like to customize the _valid modified_ styles when using the controls in an `EditForm`.
That is the following css rule:
```
.dx-blazor-checkbox.valid.modified .custom-control-input:checked+.custom-control-label::before, .dx-blazor-checkbox.valid.modified .custom-switch .custom-control-label::before, .dx-blazor-checkbox.valid.modified .custom-switch .custom-control-label::after {
    background-color: #26b050;
}
```

These rules are defined in dx-blazor.css - I guess there is currently no way to have it through custom styling (scss variable).

**Comment by outsidergiant** [comment]
Hello Sven,

Your assumption is correct. We use our own variable, which does not depend on the Bootstrap colors. We'll see if we can replace it with a Bootstrap variable. 

If the current implementation causes issues in your project, please submit a ticket to our [Support Center](http://devexpress.com/ask). We will research it separately.
