### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by Toemsel** [DevExpress/bootstrap-themes#32]
Current version equals Bootstrap version v4.5.0.
Can you please update to 5.0, or at least, to 4.6?

**Comment by outsidergiant** [comment]
Hello Toemsel,

With v21.1 our Blazor components support [v5.0](https://docs.devexpress.com/Blazor/DevExpress.Blazor.BootstrapVersion). We updated our themes:
- [Bootstrap v4.6](https://github.com/DevExpress/bootstrap-themes/tree/master/dist)
- [Bootstrap v5.0](https://github.com/DevExpress/bootstrap-themes/tree/master/dist.v5)
